//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDatagridSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users: IEntity
    {
        public int UsersID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string BirthDate { get; set; }
        public string AddressStreet { get; set; }
        public string AddressCity { get; set; }
        public string AddressCountry { get; set; }
        public string Company { get; set; }
        public string StartedWorking { get; set; }

        public int Id
        {
            get
            {
                return this.UsersID;
            }
        }
    }
}
